services:
  accountsdb:
    image: mysql
    container_name: accountsdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: "accountsdb"
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - eazybank

  loansdb:
    image: mysql
    container_name: loansdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: "loansdb"
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - eazybank

  cardsdb:
    image: mysql
    container_name: cardsdb
    ports:
      - "3309:3306"
    environment:
      MYSQL_DATABASE: "cardsdb"
      MYSQL_ROOT_PASSWORD: "root"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - eazybank

  configserver:
    image: "bachinaganesh/configserver:v1"
    container_name: configserver-ms
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank

  accounts:
    image: "bachinaganesh/accounts:v1"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    depends_on:
      configserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: qa
      SPRING_APPLICATION_NAME: "accounts"
      SPRING_DATASOURCE_URL: "jdbc:mysql://accountsdb:3306/accountsdb"
      SPRING_DATASOURCE_PASSWORD: "root"

  cards:
    image: "bachinaganesh/cards:v1"
    container_name: cards-ms
    ports:
      - "9000:9000"
    depends_on:
      configserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: qa
      SPRING_APPLICATION_NAME: "cards"
      SPRING_DATASOURCE_URL: "jdbc:mysql://cardsdb:3306/cardsdb"
      SPRING_DATASOURCE_PASSWORD: "root"

  loans:
    image: "bachinaganesh/loans:v1"
    container_name: loans-ms
    ports:
      - "8090:8090"
    depends_on:
      configserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://configserver:8071/"
      SPRING_PROFILES_ACTIVE: qa
      SPRING_APPLICATION_NAME: "loans"
      SPRING_DATASOURCE_URL: "jdbc:mysql://loansdb:3306/loansdb"
      SPRING_DATASOURCE_PASSWORD: "root"

networks:
  eazybank:
    driver: bridge
