spring:
  application:
    name: accounts
  config:
    import: configserver:http://localhost:8071
  datasource:
    url: jdbc:mysql://localhost:3306/account_db
    username: root
    password: NewPassword123!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
